<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;
use App\Models\Customer;


class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Customer::insert(
            [
                [
                    'cus_name' => 'Nguyễn Thị Thảo',
                    'phone' => '0988778892',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1995-03-10'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Trần Thị Bích',
                    'phone' => '0456789123',
                    'address' => 'Phương Liệt, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1976-08-21'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Lý Quốc Gia',
                    'phone' => '0789012345',
                    'address' => 'Chí Linh, Hải Dương',
                    'dateofbirth' =>Carbon::createFromFormat('Y-m-d', '1990-06-10'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                
                [
                    'cus_name' => 'Nguyễn Văn Anh',
                    'phone' => '0987654321',
                    'address' => 'Hà Đông, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1988-05-12'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                
                
                [
                    'cus_name' => 'Phạm Minh Châu',
                    'phone' => '0234567891',
                    'address' => 'Thanh Oai, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1982-11-30'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'cus_name' => 'Lê Văn Dũng',
                    'phone' => '0567890123',
                    'address' => 'Hai Bà Trưng, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1979-09-14'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                
                [
                    'cus_name' => 'Hoàng Thị Em',
                    'phone' => '0345678901',
                    'address' => 'Gia Lâm, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1993-02-28'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'cus_name' => 'Đặng Thị Hiền',
                    'phone' => '0678901234',
                    'address' => 'Hoài Đức, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1985-07-08'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'cus_name' => 'Đỗ Hoài Nam',
                    'phone' => '0213456789',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1971-05-12'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Mai Quốc Phong',
                    'phone' => '0657890123',
                    'address' => 'Tây Hồ, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1987-04-25'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Bùi Thị Nam',
                    'phone' => '0678901234',
                    'address' => 'Hai Bà Trưng, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1996-10-09'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Nguyễn Thị Sáu',
                    'phone' => '0768901234',
                    'address' => 'Thạch Thất, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1980-01-15'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Trương Minh Ngọc',
                    'phone' => '0456789123',
                    'address' => 'Ba Đình, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1992-03-11'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Nguyễn Thanh Nhàn',
                    'phone' => '0325678901',
                    'address' => 'Tây Hồ, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1974-09-18'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Nông Thị Giang',
                    'phone' => '0988756342',
                    'address' => 'Hoàn Kiếm, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1989-06-22'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Vưong Quốc Anh',
                    'phone' => '0503305655',
                    'address' => 'Cầu Giấy, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1978-03-07'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Trần Khánh Vinh',
                    'phone' => '0909876543',
                    'address' => 'Tây Hồ, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1983-08-14'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Hoàng Minh Tuấn',
                    'phone' => '0503305655',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1998-01-12'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Bùi Xuân Đạt',
                    'phone' => '0999777666',
                    'address' => 'Hai Bà Trưng, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1972-07-26'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Nguyễn Thị Nhung',
                    'phone' => '0943210987',
                    'address' => 'Hoàng Mai, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1986-05-09'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Vũ Minh Quân',
                    'phone' => '0912345678',
                    'address' => 'Thanh Xuân, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1991-02-19'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Đỗ Thị Hoa',
                    'phone' => '0988777666',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1977-10-04'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Lê Văn Minh',
                    'phone' => '0956789012',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1984-01-28'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Mai Văn Phú',
                    'phone' => '0900011122',
                    'address' => 'Tây Hồ, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1997-09-03'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Phạm Thị Thu',
                    'phone' => '0978999888',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1975-04-13'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Đặng Thị Thảo',
                    'phone' => '0932109876',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1981-11-20'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Nguyễn Quang Huy',
                    'phone' => '0967890123',
                    'address' => 'Hoàng Mai, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1994-08-02'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Trần Thị Phượng',
                    'phone' => '0987654321',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1970-06-15'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Hoàng Văn Anh',
                    'phone' => '0954321098',
                    'address' => 'Hai Bà Trưng, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1989-03-25'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Lê Thị Huệ',
                    'phone' => '0976543210',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1982-12-08'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Nguyễn Văn Sơn',
                    'phone' => '0999888777',
                    'address' => 'Tây Hồ, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1996-07-11'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Vũ Thị Loan',
                    'phone' => '0901234567',
                    'address' => 'Thanh Xuân, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1978-05-23'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Trần Văn Toàn',
                    'phone' => '0965432109',
                    'address' => 'Hà Đông, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1985-02-05'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Bùi Thị Kim',
                    'phone' => '0909876543',
                    'address' => 'Thanh Xuân,Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1990-09-29'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Phan Đức Hải',
                    'phone' => '0999777666',
                    'address' => 'Hai Bà Trưng, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1973-04-02'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Đinh Thị Hòa',
                    'phone' => '0943210987',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1987-11-11'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Nguyễn Văn Nam',
                    'phone' => '0912345678',
                    'address' => 'Thanh Xuân, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1971-08-24'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Trịnh Thị Ngọc',
                    'phone' => '0988777666',
                    'address' => 'Hoàng Mai, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1984-06-05'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Đặng Quang Thắng',
                    'phone' => '0956789012',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1999-01-18'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Lê Thị Tuyết',
                    'phone' => '0966785326',
                    'address' => 'Hai Bà Trưng, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1976-10-31'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Lê Văn Tâm',
                    'phone' => '0900011122',
                    'address' => 'Tây Hồ, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1992-05-14'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Nguyễn Thị Hà',
                    'phone' => '0123456788',
                    'address' => 'Hoàng Mai, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1980-02-27'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Trần Văn Bình',
                    'phone' => '0123456787',
                    'address' => 'Ba Đình, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1974-09-09'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Lê Hoàng Anh',
                    'phone' => '0123456786',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1989-07-22'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Phạm Thu Hương',
                    'phone' => '0123456785',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1977-03-04'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Võ Đức Thắng',
                    'phone' => '0909876543',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1983-11-17'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Bùi Thị Mai',
                    'phone' => '0235563450',
                    'address' => 'Thanh Xuân, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1998-08-01'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Đỗ Quang Huy',
                    'phone' => '0925347861',
                    'address' => 'Nam Từ Liêm, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1975-06-24'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Mai Ngọc Anh',
                    'phone' => '0897652143',
                    'address' => 'Hà Đông, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1991-02-08'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Nguyễn Minh Hòa',
                    'phone' => '0653148792',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1986-09-21'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Hoàng Thị Nga',
                    'phone' => '0894325671',
                    'address' => 'Đống Đa, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1972-05-03'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Trịnh Anh Tuấn',
                    'phone' => '0234568791',
                    'address' => 'Ba Đình, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1987-12-16'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Lê Thị Hồng',
                    'phone' => '0125437698',
                    'address' => 'Long Biên, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1979-10-28'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Ngô Thành Long',
                    'phone' => '0123456780',
                    'address' => 'Tây Hồ, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1993-07-13'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Phan Thị Thu Trang',
                    'phone' => '0212345678',
                    'address' => 'Thanh Xuân, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1985-03-26'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Lý Thị Phương',
                    'phone' => '0987654932',
                    'address' => 'Hoàng Mai, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1990-11-09'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Đào Minh Tuấn',
                    'phone' => '0208765431',
                    'address' => 'Thanh Xuân, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1974-08-22'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Trần Ngọc Hân',
                    'phone' => '0509876532',
                    'address' => 'Hoàn Kiếm, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1981-06-03'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Bùi Văn Nam',
                    'phone' => '0899893178',
                    'address' => 'Hoàn Kiếm, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1996-01-16'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'cus_name' => 'Lương Thị Thu Hà',
                    'phone' => '0963856734',
                    'address' => 'Tây Hồ, Hà Nội',
                    'dateofbirth' => Carbon::createFromFormat('Y-m-d', '1978-09-30'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
