<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;
use App\Models\Invoice;

class InvoiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Invoice::insert(
            [
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-09-30'),
                    'point_used' => 2,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-11-12'),
                    'point_used' => 96,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-12-11'),
                    'point_used' => 98,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-09-15'),
                    'point_used' => 50,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-08-18'),
                    'point_used' => 65,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-09-19'),
                    'point_used' => 95,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-04-12'),
                    'point_used' => 45,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-03-11'),
                    'point_used' => 200,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-08-22'),
                    'point_used' => 120,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-11-17'),
                    'point_used' => 350,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-02-12'),
                    'point_used' => 99,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-07-18'),
                    'point_used' => 50,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-05-14'),
                    'point_used' => 88,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-07-12'),
                    'point_used' => 55,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-02-17'),
                    'point_used' => 55,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-04-16'),
                    'point_used' => 90,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-08-25'),
                    'point_used' => 30,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-07-18'),
                    'point_used' => 20,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-01-12'),
                    'point_used' => 91,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-10-11'),
                    'point_used' => 450,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-05-11'),
                    'point_used' => 300,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-10-15'),
                    'point_used' => 450,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-05-24'),
                    'point_used' => 100,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-06-24'),
                    'point_used' => 400,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-01-19'),
                    'point_used' => 250,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-01-30'),
                    'point_used' => 900,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-06-07'),
                    'point_used' => 500,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-07-09'),
                    'point_used' => 300,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-07-21'),
                    'point_used' => 20,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-01-23'),
                    'point_used' => 30,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-06-13'),
                    'point_used' => 150,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-09-17'),
                    'point_used' => 19,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-08-30'),
                    'point_used' => 200,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-07-15'),
                    'point_used' => 15,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-03-12'),
                    'point_used' => 96,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-02-11'),
                    'point_used' => 20,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-01-23'),
                    'point_used' => 90,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-09-31'),
                    'point_used' => 35,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-03-30'),
                    'point_used' => 100,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-07-31'),
                    'point_used' => 15,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-12-01'),
                    'point_used' => 40,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-11-30'),
                    'point_used' => 35,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-08-12'),
                    'point_used' => 20,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'invoice_date' => Carbon::createFromFormat('Y-m-d', '2023-05-30'),
                    'point_used' => 50,
                    'customer_id' => rand(1,60),
                    'cashier_id' => rand(1,20),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
