version: "3.8"

services:
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    container_name: manage-invoice-db
    environment:
      MYSQL_ROOT_PASSWORD: manage_invoice_payment
      MYSQL_USER: manage_invoice_payment
      MYSQL_PASSWORD: manage_invoice_payment
      TZ: "Asia/Ho_Chi_Minh"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3305:3306
    user: mysql

  php:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: manage-invoice-php
    links:
      - mysql:mysql
    ports:
      - "9000:9000"
    volumes:
      - .:/application
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  webserver:
    image: nginx:1.17.10
    container_name: manage-invoice-webserver
    working_dir: /application
    links:
      - php:fpm
    environment:
      - FPM_HOST=fpm
      - FPM_PORT=9000
    volumes:
      - .:/application
      - ./:/var/www/html
      - ./storage/logs/nginx/:/var/log/nginx
      - ./docker/nginx_conf:/etc/nginx/conf.d/
    ports:
      - "8010:80"
